on:

  workflow_dispatch:  #Please remove this line
      
jobs:

  enable-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Create root directory
        run: |
          mkdir enable-github-actions
          cd enable-github-actions
      - name: Enable Github actions workflows
        shell: bash
        continue-on-error: true
        env:
         GH_TOKEN: ${{ secrets.CD_PAT }}
        run: |
          file="repo.txt"
          while read -r line; do
              echo "Processing repository $line"
              mkdir "$line"
              cd $line
              echo "echo Get workflows id"
              gh api \
              -H "Accept: application/vnd.github+json" \
              /repos/amornc/$line/actions/workflows | jq '.workflows | .[].id' >> $line-WorkflowId.txt
              echo "################################################################"
              echo "echo file $line-WorkflowId before insert string"
              cat $line-WorkflowId.txt
              echo "################################################################"
              echo "/repos/amornc/$line/actions/workflows/" >> $line-WorkflowPath.txt
              echo "echo file $line-WorkflowPath.txt"
              cat $line-WorkflowPath.txt
              echo "################################################################"
              ## replace workflow id
              sed -ie 's/^/\/repos\/amornc\/'$line'\/actions\/workflows\//' $line-WorkflowId.txt
              sed -ie 's/$/\/enable/' $line-WorkflowId.txt
              echo "echo file $line-WorkflowId after insert string"
              cat $line-WorkflowId.txt
              echo "################################################################"
              echo "Enabling $line workflows"
              file=$line-WorkflowId.txt
              while read -r ID; do
                  gh api \
                   --method PUT \
                   -H "Accept: application/vnd.github+json" \
                   $ID
              done <$file
              echo "################################################################"
              echo "Enabled $line workflows"
              echo "################################################################"
              cd .. 
          done <$file

      - name: Get Github actions workflows status
        shell: bash
        continue-on-error: true
        env:
         GH_TOKEN: ${{ secrets.CD_PAT }}
        run: |
          file="repo.txt"
          while read -r line; do
              cd $line
              gh api \
              -H "Accept: application/vnd.github+json" \
              /repos/amornc/$line/actions/workflows | jq '.workflows | .[].id' >> $line-StatusId.txt
              echo "Get $line workflows status"
              file=$line-StatusId.txt
              while read -r STATUS; do
                  echo ID=$(gh api \
                  -H "Accept: application/vnd.github+json" \
                   /repos/amornc/$line/actions/workflows/$STATUS | jq '.id') 
                  echo NAME=$(gh api \
                  -H "Accept: application/vnd.github+json" \
                   /repos/amornc/$line/actions/workflows/$STATUS | jq '.name')
                  echo STATUS=$(gh api \
                  -H "Accept: application/vnd.github+json" \
                   /repos/amornc/$line/actions/workflows/$STATUS | jq '.state')
                   echo "----------------------------------------------------------------"
              done <$file
              echo "#################################################################"
              cd .. 
          done <$file 
